name: Data-Preprocessing CICD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Temporarily save build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: target
          retention-days: 0
  docker:
    name: Deploy Docker Image
    runs-on: ubuntu-latest
    needs: build
    env:
      REPO: ${{ secrets.MLOPS_DP_DOCKER_REPO }}
    steps:
      - uses: actions/checkout@v2
      - name: Docker Hub Sign-in
        run: docker login --username=${{ secrets.MLOPS_DP_DOCKER_ID }} --password=${{ secrets.MLOPS_DP_DOCKER_PW }}
      - name: Building Docker Image
        run: docker build -t ${{ secrets.MLOPS_DP_DOCKER_REPO }}:latest -t ${{ secrets.MLOPS_DP_DOCKER_REPO }}:${GITHUB_RUN_ID} .
      - name: Publish Docker Image
        run: docker push ${{ secrets.MLOPS_DP_DOCKER_REPO }}
